---
- name: upgrade all packages
  yum: name=* state=latest

- name: EPEL repo
  raw: rpm -q /epel-release-latest-7 || rpm -U --replacepkgs https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  tags:
  - el7

- name: install basic packages
  yum: name="{{ item }}" state=latest
  with_items:
    - curl
    - git
    - ansible
    - libffi-devel
    - openssl-devel
    - gcc
    - polkit
    - java-1.8.0-openjdk.x86_64
    - python-pip
    - python3
    - python3-pip
    - jq
    - wget
    - fabric
  tags:
    - yum packages

- name: install pip requirements
  pip: name="{{ item }}" state=present
  with_items:
    - boto3
    - jinja2
  tags:
    - pip

- name: install click6.7
  pip: name=click state=present version=6.7
  tags:
    - pip

- name: install cli53
  get_url:
    url: "https://github.com/barnybug/cli53/releases/download/{{ cli53_version }}/cli53-linux-amd64"
    dest: /usr/local/bin/cli53
    owner: "{{ user }}"
    validate_certs: no
    mode: 0755

- name: Unarchive terraform from hashicorp
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: yes

- name: Unarchive packer from hashicorp
  unarchive: 
    src: "https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: yes

- import_tasks: docker.yaml
  tags:
    - docker

- import_tasks: codecommit.yaml
  tags:
    - codecommit
