# generate_server_certs.yml 

- name: Create server key
  command: openssl genrsa -out server-key.pem 4096
  args:
    chdir: "{{ dds_cert_path }}/"
    creates: server-key.pem

- name: Create the server CSR 
  command: openssl req -subj '/CN={{ dds_name }}' -sha256 -new -key server-key.pem -out server.csr
  args:
    chdir: "{{ dds_cert_path }}/"
    creates: server.csr

- name: Remove extfile
  file:
    state: absent
    path: "{{ dds_cert_path }}/extfile.cnf" 

- name: Create extfile
  file:
    state: touch 
    path: "{{ dds_cert_path }}/extfile.cnf" 

- name: Add alt name to extfile
  lineinfile:
    dest: "{{ dds_cert_path }}/extfile.cnf" 
    line: "subjectAltName = DNS:{{ dds_name }},IP:127.0.0.1"

- name: Create the server certificate 
  command: openssl x509 -req -days 9999 -sha256 -in server.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out server-cert.pem -extfile extfile.cnf
  args:
    chdir: "{{ dds_cert_path }}/"
    creates: server-cert.pem

- name: Set file permissions 
  file:
    dest: "{{ dds_cert_path }}/"
    mode: 0400
    owner: root
    group: root
